version: "3.9"
services:
 database:
  image: postgres
  container_name: database_bookAddress
  restart: always
  ports:
   - 5433:5432
  environment:  
   - POSTGRES_USER=root
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=bookAddress
  volumes:
   - pgdata:/data/postgres

 app:
  build: . 
  container_name: bookAddress
  ports:
   - 3333:3333
  volumes:  
   - .:/usr/app
  links:
   - database
  depends_on: 
   - database


volumes:
 pgdata:
  driver: local
